name = "HybridAStar"
uuid = "123b5ccf-89cf-4973-9536-c0f20d353bb2"
authors = ["Himanshu Gupta"]
version = "1.0.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"

[compat]
julia = "1"
DataStructures = "0.18"
